### ISSUE TITLE
Falta la versión PDF

### ISSUE THREAD

**Issue by zephiro** [DiscoverMeteor/DiscoverMeteor_Es#69]
¿Se puede crear una version en PDF como existe en el repo de version Rusa?https://github.com/DiscoverMeteor/DiscoverMeteor_Ru/blob/master/Discover%20Meteor%20Building%20RealTime%20JavaScript%20Web%20Apps.pdf  
O pueden decirme que programa se usa para crear la version PDF del libro, gracias.

**Comment by vicnala** [comment]
Hola @zephiro 

Desde aquí http://es.discovermeteor.com/pdf la puedes imprimir tú mismo en un fichero.

Saludos!
