### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by AshWilliams** [DiscoverMeteor/DiscoverMeteor_Es#70]
Links:
http://es.discovermeteor.com/chapters/getting-started/
http://es.discovermeteor.com/pdf

Mensaje de error:
A really lowlevel plumbing error occured. Please contact your local Maytag(tm) repair man.

Request URL:http://es.discovermeteor.com/pdf
Request Method:GET
Status Code:500 Internal Server Error

**Comment by vicnala** [comment]
Fixed. Look at DiscoverMeteor/DiscoverMeteorStatic@11c5851208b6a744f285d97df41ace38fb22a454
