### ISSUE TITLE
apartado difícil de comprender

### ISSUE THREAD

**Issue by duub** [DiscoverMeteor/DiscoverMeteor_Es#79]
En el capítulo ***7.5 Compensación de la latencia*** el último apartado ***Métodos que llaman a métodos*** no se si es culpa de la traducción o del texto original, pero por mas que lo leo me parece incomprensible lo que dice.

Alguien que tenga acceso al texto original estaria bien que lo revisara y  ver si se puede traducir de otra manera mas comprensible.

**Comment by gimco** [comment]
Te pego aquí los párrafos originales y la traducción actual:

### Methods Calling Methods

If you are keeping up, you might have just realized that our `post` Method is calling another Method (`posts/insert`) when we insert our post. How does this work?

> Si has estado atento, te habrás dado cuenta de que el método `post` llama a su vez a otro método (`posts/insert`) cada vez que insertamos un nuevo post. ¿Y, cómo es que esto funciona?

When the simulation (client-side version of the Method) is being run, we run `insert`'s simulation (so we insert into our client collection), but we *do not* call the real, server-side `insert`, as we expect that the *server-side* version of `post` will do this.

> Mientras se está ejecutando la simulación (la versión del método en el cliente), ejecutamos un `insert` simulado (lo insertamos en nuestra colección cliente), pero realmente *no* llamamos al `insert` del servidor, porque esperamos que sea la versión de `post` que hay en el servidor la que lo haga.

Consequently, when the server-side `post` Method calls `insert` there's no need to worry about simulation, and the insertion goes ahead smoothly.

> En consecuencia, cuando el método `post` del servidor llama a `insert` no tiene necesidad de preocuparse por la simulación, y la inserción se realiza sin problemas.

**Comment by duub** [comment]
gracias @gimco !
La traducción está bien, supongo que no termino de entenderlo porque no hay un razonamiento que haga que este comportamiento me parezca lógico.

**Comment by gimco** [comment]
Por si te sirve de alclaración:

Cada vez que desde el cliente llamas a un método remoto, esto desencadena en una petición DDP al servidor para que ejecute ese método. Las llamadas a insert/update/delete desencadenan también peticiones DDP para que el servidor ejecute esos métodos.

Ahora bien, si tienes un método que en su implementación llama a otros métodos o hace distintas llamadas insert/update/delete, cuando lo llames desde el lado cliente, sólo desencadenará una única llamada DDP, la del método inicial.

No hace falta desde el cliente volver a notificar al servidor de estas llamadas secundarias (que son ejecutadas desde dentro del método), ya que cuando el código se inicie en el lado servidor, ya se llamarán a esos otros métodos e inserts/update/deletes.

**Comment by duub** [comment]
gracias por la explicación, he ido a ver que era DDP y han aparecido un monton de conceptos que desconozco... así que me toca aprendrer un monton de cosas! :)
