### ISSUE TITLE
líneas en blanco en el código fuente

### ISSUE THREAD

**Issue by duub** [DiscoverMeteor/DiscoverMeteor_Es#86]
Las líneas que aparecen en la seguna línea de muchos ejemplos són algun tipo de bugg al generar el fichero html?

He revisado todo el código de versiones del [capítulo 13](http://es.discovermeteor.com/chapters/voting/) y no he podido encontrar en ninguna versión la línea en blanco que se muestra en la última modificación al código del fichero *client/templates/includes/header.html* al final de todo de la pàgina:

```html
<template name="header">

  <nav class="navbar navbar-default" role="navigation">
```

Creo que no afecta a la numeración de líneas para el resaltado de código fuente, pero me ha entrado un poco de rallada por un error mio al no tener en cuenta el softwrap en el editor de texto que uso y ahora dudo de todos los cambios que he hecho...

Por lo que queria preguntaros si se tiene que hacer alguna cosa especial para contar bien las líneas y que cuando se renderiza a html se muestren bien... por lo de la línea en blanco que aparece...

Voy a revisar todos los highlights que he modificado por si la he liado...

**Comment by duub** [comment]
he revisado todos mis commits y son consistentes teniendo en cuenta que:

* La primera línea és la 1 (y no la 0)
* Sin tener en cuenta la línea que aparece al renderizar el html

**Comment by vicnala** [comment]
He echado un vistazo (por encima) y parece todo bien. Además, no te preocupes @duub, el libro "sigue vivo" y vendrá alguien y nos corregirá ;)

**Comment by duub** [comment]
pues sigo con este criterio que es el que me parece que tiene mas sentido!
